# Generated by Django 3.2.4 on 2021-06-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
                ('apellido', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
            ],
        ),
    ]
